#!/bin/bash

#File: sysinfo_page
#Brief: a script to make an HTML page
#Author: Hunter Spack
#Assignment: Project 1 Scripting
#Date: 10/4/2020

# sysinfo_page - a script to make an HTML page

# constants
TITLE="$HOSTNAME System Info "
RIGHT_NOW="$(date +"%x %r %Z")"
TIME_STAMP="Updated on $RIGHT_NOW by $USER"


# Functions
#Brief: checks to make sure usre is root and exits the program if not
root_check()
{
	if [ "$(whoami)" != "root" ]; then
	echo "Sorry dude, root only"
	exit
	fi
}

#Brief: outputs release, kernel, and ip info
system_info()
{
	echo "<h2>System release info</h2>"
	echo "<pre>"
		lsb_release -a 2> /dev/null
		echo "Kernel version: $(uname -v)"
		lscpu
		echo "IP: $(ip addr)"
	echo "</pre>"

}


#brief: outputs system uptime
show_uptime()
{
	 echo "<h2>System uptime</h>"
	echo "<pre>"
		uptime
	echo "</pre>"
}

#Brief: ouputs free spce, disk space, and partitions
drive_space()
{
	echo "<h2>Filesystem spack</h2>"
	echo "<pre>"
		df
		fdisk -l
		free -h
	echo "</pre>"
}

#Brief: home directory size by user
home_space()
{
	echo "<h2>Home directory space by user</h2>"
	echo "<pre>"
		echo "Bytes Directory"
		du -s /home/* | sort -nr
	echo "</pre>"
}

#Brief: this grabs the logname and mail location of the user
name_and_mail()
{
	echo "<h2>Logname and mail</h2>"
	echo "<pre>$LOGNAME</pre>"
	echo "<pre>$MAIL</pre>"
}


#main
root_check
cat <<- _EOF_
    <html>
    <head>
        <title>$TITLE</title>
    </head>

    <body>
        <h1>$TITLE</h1>
	<p>$TIME_STAMP</p>
	$(system_info)
	$(show_uptime)
	$(drive_space)
	$(home_space)
	$(name_and_mail)
    </body>
    </html>
_EOF_
